USE [master]

GO

CREATE SERVER AUDIT SPECIFICATION [caglar1AuditSpecification]
FOR SERVER AUDIT [Audit-caglar]
ADD (FAILED_LOGIN_GROUP),
ADD (LOGIN_CHANGE_PASSWORD_GROUP),
ADD (DATABASE_CHANGE_GROUP),
ADD (DATABASE_OBJECT_CHANGE_GROUP),
ADD (BACKUP_RESTORE_GROUP),
ADD (DBCC_GROUP)

GO


